CREATE TABLE `incident_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`facilityId` int,
	`facilityName` varchar(255),
	`incidentType` enum('workplace_violence','threatening_behavior','domestic_violence','harassment','stalking','suspicious_activity','security_concern','policy_violation','other') NOT NULL,
	`severity` enum('low','moderate','high','critical') NOT NULL,
	`incidentDate` timestamp,
	`location` varchar(255),
	`description` text NOT NULL,
	`involvedParties` text,
	`witnesses` text,
	`priorIncidents` boolean DEFAULT false,
	`reportedToAuthorities` boolean DEFAULT false,
	`reporterRole` varchar(64),
	`contactEmail` varchar(320),
	`status` enum('new','under_review','resolved','referred') NOT NULL DEFAULT 'new',
	`adminNotes` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`trackingToken` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `incident_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `incident_reports_trackingToken_unique` UNIQUE(`trackingToken`)
);
