CREATE TABLE `btam_case_notes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`authorId` int NOT NULL,
	`noteType` enum('observation','interview','external_report','law_enforcement','legal','hr','general') NOT NULL,
	`content` text NOT NULL,
	`isPrivileged` boolean NOT NULL DEFAULT false,
	`attachments` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `btam_case_notes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `btam_cases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orgId` int NOT NULL,
	`caseNumber` varchar(32) NOT NULL,
	`status` enum('open','monitoring','resolved','escalated','referred_law_enforcement') NOT NULL DEFAULT 'open',
	`concernLevel` enum('pending','low','moderate','high','imminent') NOT NULL DEFAULT 'pending',
	`violenceType` enum('type_i_criminal','type_ii_client','type_iii_worker_on_worker','type_iv_personal_relationship'),
	`createdBy` int NOT NULL,
	`assignedAssessor` int,
	`linkedIncidentId` int,
	`isAnonymousReporter` boolean NOT NULL DEFAULT false,
	`confidentialityFlag` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `btam_cases_id` PRIMARY KEY(`id`),
	CONSTRAINT `btam_cases_caseNumber_unique` UNIQUE(`caseNumber`)
);
--> statement-breakpoint
CREATE TABLE `btam_management_plan` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`createdBy` int NOT NULL,
	`interventionType` enum('monitoring','hr_meeting','eap_referral','mandatory_counseling','credential_suspension','law_enforcement_notification','no_contact_order','termination_with_safety_protocol','hospitalization_referral','other') NOT NULL,
	`actionDescription` text NOT NULL,
	`responsibleParty` int,
	`dueDate` varchar(32),
	`completed` boolean NOT NULL DEFAULT false,
	`completionNotes` text,
	`nextReviewDate` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `btam_management_plan_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `btam_referral_intake` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`reporterRole` enum('hr','manager','coworker','self','anonymous') NOT NULL,
	`concernDescription` text NOT NULL,
	`dateOfConcern` varchar(32),
	`locationOfConcern` varchar(255),
	`witnessesPresent` boolean DEFAULT false,
	`immediateThreathFelt` boolean DEFAULT false,
	`weaponMentioned` boolean DEFAULT false,
	`targetIdentified` boolean DEFAULT false,
	`targetDescription` text,
	`priorIncidentsKnown` boolean DEFAULT false,
	`priorIncidentsDescription` text,
	`supportingDocuments` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `btam_referral_intake_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `btam_status_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`changedBy` int NOT NULL,
	`changedAt` timestamp NOT NULL DEFAULT (now()),
	`previousStatus` varchar(64),
	`newStatus` varchar(64),
	`previousConcernLevel` varchar(32),
	`newConcernLevel` varchar(32),
	`reason` text,
	CONSTRAINT `btam_status_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `btam_subjects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`subjectType` enum('employee','former_employee','customer_client','contractor','visitor','unknown') NOT NULL,
	`employmentStatus` enum('active','terminated','suspended','on_leave','never_employed'),
	`nameKnown` boolean NOT NULL DEFAULT false,
	`subjectAlias` text,
	`subjectContact` text,
	`department` varchar(255),
	`location` varchar(255),
	`supervisorName` varchar(255),
	`tenureYears` float,
	`recentDisciplinaryAction` boolean DEFAULT false,
	`pendingTermination` boolean DEFAULT false,
	`grievanceFiled` boolean DEFAULT false,
	`domesticSituationKnown` boolean DEFAULT false,
	`accessCredentialsActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `btam_subjects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `btam_wavr_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caseId` int NOT NULL,
	`assessorId` int NOT NULL,
	`assessedAt` timestamp NOT NULL DEFAULT (now()),
	`grievanceFixation` int DEFAULT 0,
	`grievanceFixationChange` boolean DEFAULT false,
	`grievanceWithTarget` int DEFAULT 0,
	`grievanceWithTargetChange` boolean DEFAULT false,
	`desperationHopelessness` int DEFAULT 0,
	`desperationHopelessnessChange` boolean DEFAULT false,
	`mentalHealthConcern` int DEFAULT 0,
	`mentalHealthConcernChange` boolean DEFAULT false,
	`paranoidThinking` int DEFAULT 0,
	`paranoidThinkingChange` boolean DEFAULT false,
	`depressionWithdrawal` int DEFAULT 0,
	`depressionWithdrawalChange` boolean DEFAULT false,
	`narcissisticInjury` int DEFAULT 0,
	`narcissisticInjuryChange` boolean DEFAULT false,
	`concerningCommunications` int DEFAULT 0,
	`concerningCommunicationsChange` boolean DEFAULT false,
	`weaponsInterest` int DEFAULT 0,
	`weaponsInterestChange` boolean DEFAULT false,
	`pathwayBehaviors` int DEFAULT 0,
	`pathwayBehaviorsChange` boolean DEFAULT false,
	`leakage` int DEFAULT 0,
	`leakageChange` boolean DEFAULT false,
	`priorViolenceHistory` int DEFAULT 0,
	`priorViolenceHistoryChange` boolean DEFAULT false,
	`priorMentalHealthCrisis` int DEFAULT 0,
	`priorMentalHealthCrisisChange` boolean DEFAULT false,
	`domesticViolenceHistory` int DEFAULT 0,
	`domesticViolenceHistoryChange` boolean DEFAULT false,
	`recentStressor` int DEFAULT 0,
	`recentStressorChange` boolean DEFAULT false,
	`socialIsolation` int DEFAULT 0,
	`socialIsolationChange` boolean DEFAULT false,
	`personalCrisis` int DEFAULT 0,
	`personalCrisisChange` boolean DEFAULT false,
	`helpSeeking` int DEFAULT 0,
	`helpSeekingChange` boolean DEFAULT false,
	`socialSupport` int DEFAULT 0,
	`socialSupportChange` boolean DEFAULT false,
	`futureOrientation` int DEFAULT 0,
	`futureOrientationChange` boolean DEFAULT false,
	`finalActBehaviors` int DEFAULT 0,
	`finalActBehaviorsChange` boolean DEFAULT false,
	`surveillanceOfTarget` int DEFAULT 0,
	`surveillanceOfTargetChange` boolean DEFAULT false,
	`imminentCommunication` int DEFAULT 0,
	`imminentCommunicationChange` boolean DEFAULT false,
	`computedConcernLevel` enum('low','moderate','high','imminent'),
	`totalWeightedScore` int,
	`topContributingFactors` json,
	`assessorNotes` text,
	`assessorAttestation` boolean NOT NULL DEFAULT false,
	CONSTRAINT `btam_wavr_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` ADD `btamRole` enum('none','tat_admin','assessor','reporter','read_only') DEFAULT 'none';