-- ============================================================
-- live_schema_fixes.sql — generated by scripts/diff-live-schema.mjs
-- Target: safeguard (MySQL 9.7.0)
-- Ordered safest-first: CREATE missing tables, ADD COLUMN, then MODIFY.
-- ============================================================
-- MISSING TABLES (safe: CREATE TABLE IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS `alert_events` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orgId` int NULL,
  `facilityId` int NOT NULL,
  `alertType` enum('lockdown','lockout','fire','weather') NOT NULL,
  `alertStatus` enum('active','response_in_progress','resolved') NOT NULL DEFAULT 'active',
  `messageTitle` varchar(255) NOT NULL,
  `messageBody` text NOT NULL,
  `roleInstructions` json NULL,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `resolvedAt` timestamp NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `alert_recipients` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `alertEventId` int NOT NULL,
  `userId` int NOT NULL,
  `rasRoleAtTime` enum('admin','responder','staff') NOT NULL,
  `deliveryStatus` enum('pending','delivered','failed') NOT NULL DEFAULT 'pending',
  `deliveredAt` timestamp NULL,
  `acknowledgedAt` timestamp NULL,
  `responseStatus` enum('acknowledged','responding') NULL,
  `responseUpdatedAt` timestamp NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `alert_status_updates` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `alertEventId` int NOT NULL,
  `statusType` enum('active','response_in_progress','resolved') NOT NULL,
  `shortMessage` varchar(120) NULL,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `btam_case_notes` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `caseId` int NOT NULL,
  `authorId` int NOT NULL,
  `noteType` enum('observation','interview','external_report','law_enforcement','legal','hr','general') NOT NULL,
  `content` text NOT NULL,
  `isPrivileged` boolean NOT NULL DEFAULT false,
  `attachments` json NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `btam_cases` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orgId` int NOT NULL,
  `caseNumber` varchar(32) NOT NULL UNIQUE,
  `status` enum('open','monitoring','resolved','escalated','referred_law_enforcement') NOT NULL DEFAULT 'open',
  `concernLevel` enum('pending','low','moderate','high','imminent') NOT NULL DEFAULT 'pending',
  `violenceType` enum('type_i_criminal','type_ii_client','type_iii_worker_on_worker','type_iv_personal_relationship') NULL,
  `createdBy` int NOT NULL,
  `assignedAssessor` int NULL,
  `linkedIncidentId` int NULL,
  `isAnonymousReporter` boolean NOT NULL DEFAULT false,
  `confidentialityFlag` boolean NOT NULL DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `btam_management_plan` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `caseId` int NOT NULL,
  `createdBy` int NOT NULL,
  `interventionType` enum('monitoring','hr_meeting','eap_referral','mandatory_counseling','credential_suspension','law_enforcement_notification','no_contact_order','termination_with_safety_protocol','hospitalization_referral','other') NOT NULL,
  `actionDescription` text NOT NULL,
  `responsibleParty` int NULL,
  `dueDate` varchar(32) NULL,
  `completed` boolean NOT NULL DEFAULT false,
  `completionNotes` text NULL,
  `nextReviewDate` varchar(32) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `btam_referral_intake` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `caseId` int NOT NULL,
  `reporterRole` enum('hr','manager','coworker','self','anonymous') NOT NULL,
  `concernDescription` text NOT NULL,
  `dateOfConcern` varchar(32) NULL,
  `locationOfConcern` varchar(255) NULL,
  `witnessesPresent` boolean NULL DEFAULT false,
  `immediateThreathFelt` boolean NULL DEFAULT false,
  `weaponMentioned` boolean NULL DEFAULT false,
  `targetIdentified` boolean NULL DEFAULT false,
  `targetDescription` text NULL,
  `priorIncidentsKnown` boolean NULL DEFAULT false,
  `priorIncidentsDescription` text NULL,
  `supportingDocuments` json NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `btam_status_history` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `caseId` int NOT NULL,
  `changedBy` int NOT NULL,
  `changedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `previousStatus` varchar(64) NULL,
  `newStatus` varchar(64) NULL,
  `previousConcernLevel` varchar(32) NULL,
  `newConcernLevel` varchar(32) NULL,
  `reason` text NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `btam_subjects` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `caseId` int NOT NULL,
  `subjectType` enum('employee','former_employee','customer_client','contractor','visitor','unknown') NOT NULL,
  `employmentStatus` enum('active','terminated','suspended','on_leave','never_employed') NULL,
  `nameKnown` boolean NOT NULL DEFAULT false,
  `subjectAlias` text NULL,
  `subjectContact` text NULL,
  `department` varchar(255) NULL,
  `location` varchar(255) NULL,
  `supervisorName` varchar(255) NULL,
  `tenureYears` float NULL,
  `recentDisciplinaryAction` boolean NULL DEFAULT false,
  `pendingTermination` boolean NULL DEFAULT false,
  `grievanceFiled` boolean NULL DEFAULT false,
  `domesticSituationKnown` boolean NULL DEFAULT false,
  `accessCredentialsActive` boolean NULL DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `btam_wavr_assessments` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `caseId` int NOT NULL,
  `assessorId` int NOT NULL,
  `assessedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `grievanceFixation` int NULL DEFAULT 0,
  `grievanceFixationChange` boolean NULL DEFAULT false,
  `grievanceWithTarget` int NULL DEFAULT 0,
  `grievanceWithTargetChange` boolean NULL DEFAULT false,
  `desperationHopelessness` int NULL DEFAULT 0,
  `desperationHopelessnessChange` boolean NULL DEFAULT false,
  `mentalHealthConcern` int NULL DEFAULT 0,
  `mentalHealthConcernChange` boolean NULL DEFAULT false,
  `paranoidThinking` int NULL DEFAULT 0,
  `paranoidThinkingChange` boolean NULL DEFAULT false,
  `depressionWithdrawal` int NULL DEFAULT 0,
  `depressionWithdrawalChange` boolean NULL DEFAULT false,
  `narcissisticInjury` int NULL DEFAULT 0,
  `narcissisticInjuryChange` boolean NULL DEFAULT false,
  `concerningCommunications` int NULL DEFAULT 0,
  `concerningCommunicationsChange` boolean NULL DEFAULT false,
  `weaponsInterest` int NULL DEFAULT 0,
  `weaponsInterestChange` boolean NULL DEFAULT false,
  `pathwayBehaviors` int NULL DEFAULT 0,
  `pathwayBehaviorsChange` boolean NULL DEFAULT false,
  `leakage` int NULL DEFAULT 0,
  `leakageChange` boolean NULL DEFAULT false,
  `priorViolenceHistory` int NULL DEFAULT 0,
  `priorViolenceHistoryChange` boolean NULL DEFAULT false,
  `priorMentalHealthCrisis` int NULL DEFAULT 0,
  `priorMentalHealthCrisisChange` boolean NULL DEFAULT false,
  `domesticViolenceHistory` int NULL DEFAULT 0,
  `domesticViolenceHistoryChange` boolean NULL DEFAULT false,
  `recentStressor` int NULL DEFAULT 0,
  `recentStressorChange` boolean NULL DEFAULT false,
  `socialIsolation` int NULL DEFAULT 0,
  `socialIsolationChange` boolean NULL DEFAULT false,
  `personalCrisis` int NULL DEFAULT 0,
  `personalCrisisChange` boolean NULL DEFAULT false,
  `helpSeeking` int NULL DEFAULT 0,
  `helpSeekingChange` boolean NULL DEFAULT false,
  `socialSupport` int NULL DEFAULT 0,
  `socialSupportChange` boolean NULL DEFAULT false,
  `futureOrientation` int NULL DEFAULT 0,
  `futureOrientationChange` boolean NULL DEFAULT false,
  `finalActBehaviors` int NULL DEFAULT 0,
  `finalActBehaviorsChange` boolean NULL DEFAULT false,
  `surveillanceOfTarget` int NULL DEFAULT 0,
  `surveillanceOfTargetChange` boolean NULL DEFAULT false,
  `imminentCommunication` int NULL DEFAULT 0,
  `imminentCommunicationChange` boolean NULL DEFAULT false,
  `computedConcernLevel` enum('low','moderate','high','imminent') NULL,
  `totalWeightedScore` int NULL,
  `topContributingFactors` json NULL,
  `assessorNotes` text NULL,
  `assessorAttestation` boolean NOT NULL DEFAULT false
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `drill_participants` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `sessionId` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `role` varchar(100) NULL,
  `attended` boolean NOT NULL DEFAULT true,
  `observations` text NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `drill_sessions` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `templateId` int NOT NULL,
  `facilityId` int NULL,
  `orgId` int NULL,
  `scheduledByUserId` int NOT NULL,
  `scheduledAt` timestamp NOT NULL,
  `completedAt` timestamp NULL,
  `status` enum('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'scheduled',
  `debriefData` json NULL,
  `systemIntelligence` json NULL,
  `participantCount` int NULL,
  `facilitatorNotes` text NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `drill_templates` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orgId` int NULL,
  `facilityId` int NULL,
  `createdByUserId` int NOT NULL,
  `title` varchar(255) NOT NULL,
  `drillType` enum('micro','guided','operational','extended') NOT NULL,
  `durationMinutes` int NOT NULL,
  `industry` varchar(100) NULL,
  `jurisdiction` varchar(100) NULL,
  `generationMode` enum('system','user') NOT NULL DEFAULT 'system',
  `userPrompt` text NULL,
  `content` json NOT NULL,
  `regulatoryTags` json NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `facility_alert_settings` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `facilityId` int NOT NULL UNIQUE,
  `orgId` int NULL,
  `lockdownTemplate` json NULL,
  `lockoutTemplate` json NULL,
  `pushEnabled` boolean NOT NULL DEFAULT true,
  `escalationPreferences` json NULL,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `facility_floor_maps` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `facility_id` int NOT NULL,
  `org_id` int NULL,
  `name` varchar(255) NOT NULL,
  `floor` varchar(100) NULL,
  `image_url` text NULL,
  `file_key` text NULL,
  `map_data` json NULL,
  `annotations` json NULL,
  `width` int NULL,
  `height` int NULL,
  `created_by_user_id` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `incident_communications` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `incident_id` int NOT NULL,
  `sender_role` enum('admin','reporter') NOT NULL,
  `sender_name` varchar(255) NULL,
  `message` text NOT NULL,
  `is_from_admin` boolean NOT NULL DEFAULT true,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `micro_drill_assignments` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `org_id` int NULL,
  `assigned_by_user_id` int NOT NULL,
  `assigned_to_user_id` int NULL,
  `assigned_to_name` varchar(255) NULL,
  `assigned_to_email` varchar(320) NULL,
  `drill_id` int NOT NULL,
  `drill_category` varchar(255) NOT NULL,
  `drill_title` varchar(255) NOT NULL,
  `assigned_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completion_date` timestamp NULL,
  `due_date` timestamp NULL,
  `status` enum('pending','in_progress','completed','expired') NOT NULL DEFAULT 'pending',
  `step1_choice` varchar(10) NULL,
  `step2_choices` json NULL,
  `considerations_checked` json NULL,
  `completed_at` timestamp NULL,
  `completed_by_name` varchar(255) NULL,
  `notes` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `personnel_locations` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orgId` int NOT NULL,
  `userId` int NOT NULL,
  `latitude` float NOT NULL,
  `longitude` float NOT NULL,
  `status` varchar(64) NOT NULL DEFAULT 'Active',
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `push_subscriptions` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `userId` int NOT NULL,
  `orgId` int NULL,
  `subscription` json NOT NULL,
  `endpoint` varchar(512) NULL,
  `userAgent` text NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `scan_share_tokens` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `scanId` int NOT NULL,
  `token` varchar(128) NOT NULL UNIQUE,
  `createdByUserId` int NULL,
  `expiresAt` timestamp NOT NULL,
  `revokedAt` timestamp NULL,
  `label` varchar(255) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `staff_checkins` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `orgId` int NULL,
  `facilityId` int NULL,
  `staffName` varchar(255) NOT NULL,
  `status` enum('reunification','injured','off_site','cannot_disclose') NOT NULL,
  `location` text NULL,
  `recordedByUserId` int NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `user_invites` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `email` varchar(320) NOT NULL,
  `inviteRole` enum('ultra_admin','super_admin','admin','auditor','user','viewer','sandbox') NOT NULL DEFAULT 'user',
  `token` varchar(64) NOT NULL UNIQUE,
  `invitedByUserId` int NOT NULL,
  `expiresAt` timestamp NOT NULL,
  `usedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- MISSING COLUMNS (safe: ADD COLUMN)
ALTER TABLE `api_keys` ADD COLUMN `lastUsedAt` timestamp NULL;
ALTER TABLE `api_keys` ADD COLUMN `revokedAt` timestamp NULL;
ALTER TABLE `api_keys` ADD COLUMN `expiresAt` timestamp NULL;
ALTER TABLE `audits` ADD COLUMN `executiveSummaryJson` json NULL;
ALTER TABLE `audits` ADD COLUMN `executiveSummaryGeneratedAt` timestamp NULL;
ALTER TABLE `audits` ADD COLUMN `selectedMenu` enum('a','b') NULL;
ALTER TABLE `facilities` ADD COLUMN `jurisdiction` varchar(64) NULL DEFAULT 'United States';
ALTER TABLE `facilities` ADD COLUMN `emergencyRoles` text NULL;
ALTER TABLE `facilities` ADD COLUMN `aedOnSite` boolean NULL DEFAULT false;
ALTER TABLE `facilities` ADD COLUMN `aedLocations` text NULL;
ALTER TABLE `facilities` ADD COLUMN `latitude` float NULL;
ALTER TABLE `facilities` ADD COLUMN `longitude` float NULL;
ALTER TABLE `facilities` ADD COLUMN `operationalPolicies` text NULL;
ALTER TABLE `facilities` ADD COLUMN `coordinatorContacts` text NULL;
ALTER TABLE `facilities` ADD COLUMN `emergencyContacts` text NULL;
ALTER TABLE `flagged_visitors` ADD COLUMN `orgId` int NULL;
ALTER TABLE `flagged_visitors` ADD COLUMN `flagLevel` enum('red','yellow') NOT NULL DEFAULT 'red';
ALTER TABLE `flagged_visitors` ADD COLUMN `lastEscalatedAt` timestamp NULL;
ALTER TABLE `flagged_visitors` ADD COLUMN `escalationCount` int NOT NULL DEFAULT 0;
ALTER TABLE `flagged_visitors` ADD COLUMN `photoUrl` text NULL;
ALTER TABLE `flagged_visitors` ADD COLUMN `photoFileKey` text NULL;
ALTER TABLE `incident_reports` ADD COLUMN `referredTo` int NULL;
ALTER TABLE `incident_reports` ADD COLUMN `followUpRequested` boolean NULL DEFAULT false;
ALTER TABLE `incident_reports` ADD COLUMN `followUpMethod` enum('phone','email','in_person') NULL;
ALTER TABLE `incident_reports` ADD COLUMN `followUpContact` varchar(320) NULL;
ALTER TABLE `incident_reports` ADD COLUMN `involvedPersonName` varchar(255) NULL;
ALTER TABLE `incident_reports` ADD COLUMN `isRepeatIncident` boolean NULL DEFAULT false;
ALTER TABLE `incident_reports` ADD COLUMN `repeatGroupId` varchar(64) NULL;
ALTER TABLE `incident_reports` ADD COLUMN `threatFlags` text NULL;
ALTER TABLE `incident_reports` ADD COLUMN `maxThreatSeverity` varchar(16) NULL;
ALTER TABLE `organizations` ADD COLUMN `plan` enum('free','paid') NOT NULL DEFAULT 'free';
ALTER TABLE `organizations` ADD COLUMN `planUpdatedAt` timestamp NULL;
ALTER TABLE `organizations` ADD COLUMN `externalSubscriptionId` varchar(255) NULL;
ALTER TABLE `organizations` ADD COLUMN `websiteResourceLinks` text NULL DEFAULT ('[]');
ALTER TABLE `question_flags` ADD COLUMN `orgId` int NULL;
ALTER TABLE `tester_feedback` ADD COLUMN `orgId` int NULL;
ALTER TABLE `users` ADD COLUMN `termsAcceptedAt` timestamp NULL;
ALTER TABLE `visitor_logs` ADD COLUMN `orgId` int NULL;

-- TYPE / NULLABILITY MISMATCHES (review first: may fail if existing rows violate constraints)
ALTER TABLE `api_keys` MODIFY COLUMN `userId` int NOT NULL;
ALTER TABLE `api_keys` MODIFY COLUMN `label` varchar(255) NULL;
ALTER TABLE `api_keys` MODIFY COLUMN `keyHash` varchar(128) NOT NULL;
ALTER TABLE `audit_logs` MODIFY COLUMN `action` enum('create','update','delete','login','logout','invite_sent','invite_accepted','member_removed','role_changed','audit_completed','audit_reopened','incident_submitted','incident_reviewed','report_shared','escalate') NOT NULL;
ALTER TABLE `org_invites` MODIFY COLUMN `inviteRole` enum('super_admin','admin','auditor','user','viewer','sandbox') NOT NULL DEFAULT 'user';
ALTER TABLE `org_members` MODIFY COLUMN `orgRole` enum('super_admin','admin','auditor','user','viewer','sandbox') NOT NULL DEFAULT 'user';
ALTER TABLE `training_modules` MODIFY COLUMN `playerType` enum('Articulate_Storyline_Web','external_link') NOT NULL DEFAULT 'Articulate_Storyline_Web';
ALTER TABLE `training_modules` MODIFY COLUMN `trackingType` enum('None') NOT NULL DEFAULT 'None';
ALTER TABLE `training_modules` MODIFY COLUMN `sourceFileName` varchar(255) NULL;
ALTER TABLE `training_modules` MODIFY COLUMN `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `training_modules` MODIFY COLUMN `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `users` MODIFY COLUMN `role` enum('ultra_admin','admin','super_admin','auditor','viewer','user','sandbox') NOT NULL DEFAULT 'user';
