/**
 * decisionDoctrine.ts
 *
 * Centralized Universal Decision Doctrine for the ACTD Drill Engine.
 *
 * This module defines the five core principles that govern every drill option,
 * outcome, label, and expert reasoning generated by the system.
 *
 * IMPORTANT: This doctrine does NOT replace ACTD.
 * It POWERS ACTD by evaluating decision quality across all generated drills.
 *
 * The doctrine is scenario-agnostic and transfers across:
 *   unauthorized access | suspicious object | escalating behavior |
 *   coworker concern | visitor management | environmental anomaly |
 *   threatening communication | emergency access violations
 *
 * The scenario changes. The decision doctrine does not.
 */

// ─── Core Principle Types ──────────────────────────────────────────────────────

export type DoctrinePrinciple =
  | "preserve_life_reduce_exposure"
  | "maintain_control_of_space"
  | "lowest_force_effective_response"
  | "activate_coordination_early"
  | "create_defensible_record";

export type DecisionEffect = "positive" | "neutral" | "negative";

/**
 * Five-dimension evaluation object stored on every generated response option.
 * This is computed BEFORE labels, outcomes, and expert reasoning are written.
 */
export type DecisionDoctrineEvaluation = {
  /** Principle 1: Does this action reduce immediate personal or group exposure? */
  exposure_effect: DecisionEffect;
  /** Principle 2: Does this action restore or preserve control of the environment? */
  control_effect: DecisionEffect;
  /** Principle 3: Does this action avoid unnecessary escalation or provocation? */
  escalation_effect: DecisionEffect;
  /** Principle 4: Does this action activate support or resources early? */
  coordination_effect: DecisionEffect;
  /** Principle 5: Does this action improve the ability to record and defend later? */
  documentation_effect: DecisionEffect;
  /** Optional analyst notes explaining non-obvious evaluations */
  notes?: string[];
};

// ─── Doctrine Principle Definitions (for prompt injection and UI display) ─────

export const DOCTRINE_PRINCIPLES: Record<DoctrinePrinciple, {
  label: string;
  description: string;
  actdPhase: "assess" | "commit" | "take_action" | "debrief" | "all";
}> = {
  preserve_life_reduce_exposure: {
    label: "Preserve Life & Reduce Exposure",
    description: "Every decision must prioritize reducing immediate personal and group risk. Avoid actions that increase direct exposure without a clear tactical benefit.",
    actdPhase: "assess",
  },
  maintain_control_of_space: {
    label: "Maintain Control of Space",
    description: "Decisions should preserve or restore environmental control — visibility, access management, and spatial positioning. Avoid actions that allow deeper access, concealment, or loss of visibility.",
    actdPhase: "assess",
  },
  lowest_force_effective_response: {
    label: "Lowest-Force Effective Response",
    description: "Use the minimum level of intervention required to achieve the objective. Escalating force without justification introduces liability and unpredictable subject reactions.",
    actdPhase: "commit",
  },
  activate_coordination_early: {
    label: "Activate Coordination Early",
    description: "Engage the response chain — security, management, emergency services — as early as possible. Isolated responses without backup create single points of failure.",
    actdPhase: "commit",
  },
  create_defensible_record: {
    label: "Create a Defensible Record",
    description: "Every action must be documentable and defensible. Decisions that close the documentation window or bypass notification protocols introduce organizational and legal risk.",
    actdPhase: "debrief",
  },
};

// ─── ACTD Doctrine Mapping ─────────────────────────────────────────────────────

/**
 * Maps each ACTD phase to the doctrine principles it primarily exercises.
 * Used to validate that generated ACTD content aligns with doctrine.
 */
export const ACTD_DOCTRINE_MAP = {
  assess: [
    "preserve_life_reduce_exposure",
    "maintain_control_of_space",
    "activate_coordination_early",
  ] as DoctrinePrinciple[],
  commit: [
    "lowest_force_effective_response",
    "activate_coordination_early",
  ] as DoctrinePrinciple[],
  take_action: [
    "preserve_life_reduce_exposure",
    "maintain_control_of_space",
    "lowest_force_effective_response",
  ] as DoctrinePrinciple[],
  debrief: [
    "create_defensible_record",
  ] as DoctrinePrinciple[],
};

// ─── Cross-Scenario Transferability ───────────────────────────────────────────

export type DoctrineScenarioType =
  | "unauthorized_access"
  | "suspicious_object"
  | "escalating_behavior"
  | "coworker_concern"
  | "visitor_management"
  | "environmental_anomaly"
  | "threatening_communication"
  | "emergency_access_violation";

/**
 * All eight scenario types this doctrine applies to.
 * The scenario changes. The doctrine does not.
 */
export const DOCTRINE_SCENARIO_TYPES: DoctrineScenarioType[] = [
  "unauthorized_access",
  "suspicious_object",
  "escalating_behavior",
  "coworker_concern",
  "visitor_management",
  "environmental_anomaly",
  "threatening_communication",
  "emergency_access_violation",
];

// ─── Generated Option Shape ────────────────────────────────────────────────────

/**
 * Full shape of a doctrine-evaluated response option.
 * The doctrine_evaluation is computed first; all other fields derive from it.
 */
export type GeneratedOption = {
  id: string;
  label: string;
  description: string;
  doctrine_evaluation: DecisionDoctrineEvaluation;
  outcome_summary?: string;
  tradeoff_summary?: string;
  expert_reasoning?: string;
};

// ─── Drill Scenario Shape ──────────────────────────────────────────────────────

export type DrillScenario = {
  id: string;
  title: string;
  drill_type: "micro" | "guided" | "operational" | "extended";
  primary_threat_signal: string;
  decision_pressure: string[];
  options?: GeneratedOption[];
};

// ─── Viability Standards ───────────────────────────────────────────────────────

/**
 * Four real-world viability tests every generated option must pass.
 * If an option fails any test, it must not be generated.
 */
export const OPTION_VIABILITY_STANDARDS = {
  policy_alignment: "Must reflect realistic workplace protocols (corporate, healthcare, or public safety). No actions that violate standard guidelines.",
  role_appropriateness: "Must match the authority and training level of the role described. An employee does not physically restrain; security does not abandon post without protocol.",
  escalation_awareness: "Must consider how the individual may react: comply, evade, hesitate, or escalate.",
  no_theatrical_actions: "No yelling unnecessarily, dramatic confrontation, or exaggerated behaviors. Actions must be practical, controlled, and defensible in a real training program.",
} as const;
